name: mammoth_test
version: '1.0.0'
config-version: 2
profile: 'mammoth_test'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mammoth_test:
    bronze:
      +enabled: false
    silver:
      +enabled: false
    gold:
      +enabled: false
    tpch_sf1000:
      bronze:
        +materialized: view
        +tags: ['bronze', 'tpch_sf1000']
      silver:
        +materialized: table
        +tags: ['silver', 'tpch_sf1000']
      gold:
        +materialized: table
        +tags: ['gold', 'tpch_sf1000']
    tpch_sf10:
      bronze:
        +materialized: view
        +tags: ['bronze', 'tpch_sf10']
      silver:
        +materialized: table
        +tags: ['silver', 'tpch_sf10']
      gold:
        +materialized: table
        +tags: ['gold', 'tpch_sf10']
