version: "1"
context:
  active-host: "qz679.us1.dbt.com"
  active-project: "70403103999640"
projects:
  - project-name: "mammoth-test"
    project-id: "70403103999640"
    account-name: "Cloud Analytics Consulting, LLC"
    account-id: "70403103926586"
    account-host: "qz679.us1.dbt.com"
    token-name: "cloud-cli-1f66"
    token-value: "dbtu_WDrCikcodkE_PdAjFvXl84-sCUY14JEH8djuPjrLvDvl10ZvLY"